#!/bin/sh

if [ $# -ne 1 ]; then
    echo >&2 "${0##*/} GAME.APP"
    exit 2
fi
game="$1"
norunkeyfile="$(mktemp -t "${0##*/}.XXXXXX")"
trap 'rm -f "$norunkeyfile"' EXIT INT TERM
find "$game/$(readlink "$game/Game")/" -name \*.vdf | nlxargs vdf_disable_reg 2>"$norunkeyfile" >"$game/disable_redist.reg"
sed -n -e 's/^Warning: no run key for .*: %INSTALLDIR%\\\\//p' "$norunkeyfile" | while read path; do
    path="$game/Game/$(printf "%s" "$path" | sed 's#\\#/#g')"
    if [ -e "$path" ] && [ ! -e "$path.orig" ]; then
        mv -v "$path" "$path.orig"
    fi
done
if [ $(wc -l <"$game/disable_redist.reg") -eq 0 ]; then
    rm -f "$game/disable_redist.reg"
fi
