#!/bin/sh

if [ ! -e /Volumes/My\ Passport ]; then
    echo >&2 "My Passport drive is not mounted, aborting"
    exit 1
fi
PATH="${0%/*}:$PATH"
{
    # mdfind -onlyin '/Volumes/My Passport' -attr kMDItemDisplayName "kMDItemUserTags == \"Game\""|sed 's,^/Volumes/My Passport/,,; s,/.*kMDItemDisplayName = ,/,'
    find-games | grep -E '/Volumes/(My Passport|Games Archive)/'
    find /Volumes/My\ Passport/Games*/ -iname \*.app -prune -type l -print -maxdepth 2 | sed 's,//,/,g'
    find /Volumes/Games\ Archive/Games*/ -iname \*.app -prune -type l -print -maxdepth 2 | sed 's,//,/,g'
} | grep -Ev '\.Trashes|Archived|Pending|Backup|Replaced' | \
    tr '\n' '\0' | xargs -0 identify-game-wrapper | sed 's,.unknown$,,' | \
    sed 's,/Volumes/[^/]*/,,; s,OpenEmu Library/roms/,OpenEmu/,; s,^games,Games,; s,- broken,- Broken,;' | sort -u
