#!/bin/sh

find_app_symlinks_resolved () {
    find "$@" -iname \*.app -prune -type l -print -maxdepth 3 | \
        tr '\n' '\0' | xargs -0 -n 1 abs_readlink
}

{
    # mdfind -onlyin '/Volumes/My Passport' -attr kMDItemDisplayName "kMDItemUserTags == \"Game\""|sed 's,^/Volumes/My Passport/,,; s,/.*kMDItemDisplayName = ,/,'
    # find-games | grep -E '/Volumes/(My Passport|Games Archive)/'
    find /Volumes/My\ Passport/Games*/ -iname \*.app -prune -type d -print | grep -Ev 'Setup|Launcher|-64'
    # find_app_symlinks_resolved /Volumes/My\ Passport/Games*/
    find /Volumes/My\ Passport/Games*/ -iname \*.app -prune -type l -print
    if [ ! -e /Volumes/Games\ Archive ]; then
        echo >&2 "Warning: Games Archive is not mounted"
    fi
    # find_app_symlinks_resolved /Volumes/Games\ Archive/Games*/
    find /Volumes/Games\ Archive/Games*/ -iname \*.app -prune -type d -print | grep -Ev 'Setup|Launcher|-64'
    find /Volumes/Games\ Archive/Games*/ -iname \*.app -prune -type l -print
    find /Volumes/My\ Passport/OpenEmu\ Library/roms/ -type f -not -name .DS_Store
} | sed 's,//,/,g' | grep -Ev '\.Trashes|Archived|Pending|Backup|Replaced|Utilities|Apps|Experimental|Replaced|Obsolete'
