#!/bin/sh

PATH="$(dirname "$0"):$PATH"
appid="$1"
appinfo="$(mktemp -t "${0##*/}.XXXXX")" || exit $?
trap 'rm -f "$appinfo"' EXIT INT TERM
steamcmd.sh +app_info_print "$appid" +quit | tail +8 >"$appinfo"
for i in $(seq 0 10); do
    oslist="$(vdf-get "$appid.config.launch.$i.config.oslist" <"$appinfo" 2>/dev/null)"
    oslist="$(echo "$oslist" | tr ',' ' ')"
    if [ -z "$oslist" ] || echo "$oslist" | grep -qw windows; then
        if exe="$(vdf-get "$appid.config.launch.$i.executable" <"$appinfo" 2>/dev/null)" && [ -n "$exe" ]; then
            echo "$exe" | sed -e 's#\\\\#/#g; s#\\#/#g;'
            break
        fi
    fi
done
