#!/bin/sh

PATH="$(dirname "$0"):$PATH"

ret=0
for appid; do
    icon="steam-app-info "$appid" | vdf-get "$appid.common.icon")"
    if [ -z "$icon" ]; then
        echo >&2 "Error: no icon found in appid info for $appid?"
        ret=1
        continue
    fi
    curl -fLlo "$appid.jpg" "https://steamcdn-a.opskins.media/steamcommunity/public/images/apps/${appid}/${icon}.jpg" \
        && makeicns -in "$appid.jpg" -out "$appid.icns" || ret=3
done
exit "$ret"
