#!/bin/bash

relpath () {
    python -c "import os, sys; print(os.path.relpath(*sys.argv[1:]))" "$@"
}

get_gamedir () {
    type="${2:-$(identify-game-wrapper -q "$game")}"
    if [ "$type" = "gog" ]; then
        # Grab underlying app
        exclude_game="$(echo "$game/Contents/Resources/game/"*.app)"
        if [ -z "$exclude_game" ]; then
            exit 1
        fi
        type="${2:-$(identify-game-wrapper -q "$exclude_game")}"
    fi

    case "$type" in
        "dos (boxer standalone)")
            boxer="$(find "$exclude_game/Contents/Resources/" -iname \*.boxer -maxdepth 1)"
            if [ -z "$boxer" ]; then
                echo >&2 "Error: Unable to locate .boxer for boxer standalone"
                exit 1
            fi

            if [ ! -e "$boxer/C.harddisk" ]; then
                echo >&2 "Error: no C.harddisk?"
                exit 1
            fi

            if [ $(find "$boxer/C.harddisk" -mindepth 1 -maxdepth 1 | wc -l) -eq 1 ]; then
                dir="$(find "$boxer/C.harddisk" -mindepth 1 -maxdepth 1)"
                gamedir="$boxer/C.harddisk/$dir"
            else
                gamedir="$boxer/C.harddisk"
            fi
            ;;
        "windows (wineskin)")
            if [ "$(/usr/libexec/PlistBuddy -c 'Print :CFBundleExecutable' "$game/Contents/Info.plist")" = "GOGLauncher" ]; then
                # Grab underlying app
                exclude_game="$(echo "$game/Contents/Resources/game/"*.app)"
            fi

            gameexe="$(/usr/libexec/PlistBuddy -c 'Print "Program Name and Path"' "$exclude_game/Contents/Info.plist")" || {
                printf >&2 "Error extracting path for '%s'\n" "$exclude_game"
                exit 1
            }
            gamedir="${gameexe%/*}"
            if [ -e "$exclude_game/drive_c" ]; then
                drive="$exclude_game/drive_c"
            else
                drive="$exclude_game/Contents/Resources/drive_c"
            fi
            ;;
        "windows (cider)")
            gamedir="$(/usr/libexec/PlistBuddy -c 'Print "CedegaGameDir"' "$game/Contents/Info.plist")" || exit 1
            gamedir="${gamedir#C:}"
            gamedir="$(printf '%s' "$gamedir" | tr "\\" '/')"
            drive="$game/Contents/Resources/transgaming/c_drive"
            ;;
        *)
            exit 1
            ;;
    esac
}

gamedir=
game="$1"
exclude_game="$game"
if [ -L "$game/Game" ]; then
    if [ -e "$(abs_readlink "$game/Game")" ]; then
        gamedir="$(readlink "$game/Game")"
    else
        echo >&2 "Warning: 'Game' symlink is dead"
    fi
fi
if [ -z "$gamedir" ]; then
    get_gamedir
fi

if [ -z "$drive" ]; then
    drive="$exclude_game/drive_c"
    if [ ! -e "$drive" ]; then
        echo >&2 "Error: drive not set?"
        exit 1
    fi
fi
gamedir="${gamedir#/}"
case "$gamedir" in
    "$exclude_game"/)
        ;;
    *)
        gamedir="$exclude_game/$gamedir"
        ;;
esac
if [ -n "$drive" ]; then
    drive="$(relpath "$drive" "$exclude_game")"
    rel_gamedir="$(relpath "$gamedir" "$exclude_game/$drive")"
    if [ "$rel_gamedir" = "Program Files/Steam" ]; then
        gamedir="$(cd "$game/$drive" && find "$gamedir/SteamApps/common" -type d -mindepth 1 -maxdepth 1 | head -n 1)"
    elif [ "$rel_gamedir" = "Program Files/GalaxyClient" ]; then
        gamedir="$(cd "$game/$drive" && find "GOG Games" -type d -mindepth 1 -maxdepth 1 | head -n 1)"
    else
        gamedir="$rel_gamedir"
    fi
    echo "$drive/$gamedir"
else
    echo "$gamedir"
fi
