#!/bin/sh

PATH="$(dirname "$0"):$PATH"
if [ $# -eq 0 ]; then
    echo >&2 "Usage: ${0##*/} APPID [APPID..]"
    exit 1
fi

for appid; do
    for i in $(seq 0 10); do
        exe="$(steam-app-info "$appid" | vdf-get "$appid.config.launch.$i.executable" 2>/dev/null)"
        if [ -n "$exe" ]; then
            oslist="$(steam-app-info "$appid" | vdf-get "$appid.config.launch.$i.config.oslist" 2>/dev/null)"
            if [ -z "$oslist" ] || echo "$oslist" | tr ',' ' ' | grep -qw windows; then
                echo "$exe" | sed -e 's#\\\\#/#g; s#\\#/#g;' | tr -d '\n'
                args="$(steam-app-info "$appid" | vdf-get "$appid.config.launch.$i.arguments" 2>/dev/null)"
                if [ -n "$args" ]; then
                    echo " $args"
                else
                    echo
                fi
                exit 0
            fi
        fi
    done
done

echo >&2 "Error: no exe for $appid"
exit 1