#!/bin/bash

set -euo pipefail
trap "echo 'error: Script failed: see failed command above'" ERR

ddg () {
    http --check-status --ignore-stdin https://duckduckgo.com/html/ q=="$*" | pup '.links_main > a attr{href}'
}

metacritic_search () {
    ddg site:metacritic.com/game/pc/ "$*" | sed -n 's/\(.*\/game\/[^\/]*\/[^\/]*\).*/\1/p'
}

metacritic_score () {
    http --check-status --ignore-stdin "$@" | pup '.metascore_anchor .metascore_w span text{}'
}

metacritic_link="$(metacritic_search "$*" | head -n 1)"
if [ -z "$metacritic_link" ]; then
    echo >&2 "Error: no link for $*"
    exit 1
fi

score="$(metacritic_score "$metacritic_link")"
if [ -z "$score" ]; then
    score=0
fi
echo "$score"
