#!/bin/bash

set -euo pipefail
trap "echo 'error: Script failed: see failed command above'" ERR

metacritic_score () {
    http --check-status --ignore-stdin "$@" | pup '.metascore_anchor .metascore_w span text{}'
}

metacritic_search () {
    metacritic_root="http://www.metacritic.com"
    http --check-status --ignore-stdin "${metacritic_root}/search/game/$*/results" | pup 'a.col_left attr{href}' | sed "s,^,$metacritic_root,"
}

metacritic_link="$(metacritic_search "$*" | head -n 1)"
if [ -z "$metacritic_link" ]; then
    echo >&2 "Error: no link for $*"
    exit 1
fi

score="$(metacritic_score "$metacritic_link")"
if [ -z "$score" ]; then
    score=0
fi
echo "$score"
