#!/bin/sh

for app; do
    if [ -h "$app/Game" ]; then
        gamedir="$(cd "$app" && abspath "$(readlink Game)")"
        if [ -h "$gamedir" ]; then
            move-dir-back-in "$gamedir"
        else
            move-dir-out "$gamedir"
        fi
    fi
done
