#!/bin/sh
# Print the wrappers which could be handled by wrap-native

tempfile="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
trap 'rm -f "$tempfile"' EXIT INT TERM

PATH="$(cd "$(dirname "$0")" && pwd):$PATH"
find . -iname \*.app -prune | while read app; do
    game_base="${app##*/}"
    if [ -e "$app/Contents/Resources/$game_base" ]; then
        # Already native, skip
        continue
    fi

    wrap-native -n "$app" >"$tempfile" 2>/dev/null
    if [ $? -eq 0 ]; then
        printf '%s: %s\n' "$app" "$(sed -En 's/(Game type|ScummVM Game ID): //p' "$tempfile" | tr '\n' ' ')"
    fi
done 2>&1 | grep -v 'unknown game type'
