#!/usr/bin/env python

import ConfigParser
import os
import sys

if len(sys.argv) <= 1:
    sys.exit('Usage: %s CONFIGFILE' % os.path.basename(sys.argv[0]))

cfgfn = sys.argv[1]
config = ConfigParser.RawConfigParser()
config.read(cfgfn)

if not os.path.exists(cfgfn + '.bak'):
    with open(cfgfn + '.bak', 'wb') as bakfile:
        config.write(bakfile)

config.set('scummvm', 'multi_midi', 'true')
config.set('scummvm', 'music_driver', 'core')
config.set('scummvm', 'aspect_ratio', 'true')
config.set('scummvm', 'gfx_mode', 'opengl_linear')
#config.set('scummvm', 'gfx_mode', 'AdvMAME3x')

with open(cfgfn, 'wb') as cfgfile:
    config.write(cfgfile)
