#!/bin/sh

alias mv="mv -v"
for game; do
    game_base="${game##*/}"
    if ! [ -e "$game/Contents/Resources/$game_base" ]; then
        echo >&2 "Warning: unrecognized native game $game"
        continue
    fi

    original="$game/Contents/Resources/$game_base"
    if [ -h "$original/Game" ]; then
        orig_game_dir="$original/$(readlink "$original/Game")"
        rm -fv "$orig_game_dir/"bxlaunch*.bat
        if [ -L "$orig_game_dir" ]; then
            real_game_dir="$(cd "$orig_game_dir" && pwd -P)"
            if [ -e "$real_game_dir" ]; then
                rm "$orig_game_dir"
                mv "$real_game_dir" "$orig_game_dir"
            fi
        fi
    fi
    games_dir="$(dirname "$game")"
    tmp="$(mktemp -d "$games_dir/${0##*/}.XXXXXX")"
    trap 'rm -rf "$tmp"' EXIT INT TERM
    mv "$game" "$tmp/"
    mv "$tmp/${original#$games_dir/}" "$games_dir/"
    rm -rf "$tmp"
done
