#!/usr/bin/env python2

import vdf
import sys

obj = vdf.load(sys.stdin)
for key in sys.argv[1:]:
    value = reduce(lambda x, y: x[y], key.split("."), obj)
    if isinstance(value, str):
        print(value)
    else:
        vdf.dump(value, sys.stdout)
