#!/usr/bin/env python

import acf
import sys

def get_val_nocase(path, acfdata):
    elements = path.split('.')
    current = acfdata
    while elements:
        currentkey = elements.pop(0)
        for key, value in current.items():
            if key.lower() == currentkey.lower():
                current = value
                break
        else:
            return
    return current

keys = []
for fn in sys.argv[1:]:
    data = acf.parse_acf(fn)
    runp = get_val_nocase('installscript.run process', data)
    for name, runpinfo in runp.items():
        key = get_val_nocase('hasrunkey', runpinfo)
        if key:
            key = key.replace('\\\\', '\\')
            keys.append((key, name))

print("REGEDIT4")
print("")
for key, name in sorted(keys):
    print("[{}]".format(key))
    print('"{}"=dword:00000001'.format(name))
    print("")
