#!/usr/bin/env python

import sys
import vdf


def get_val_nocase(path, acfdata):
    elements = path.split('.')
    current = acfdata
    while elements:
        currentkey = elements.pop(0)
        for key, value in current.items():
            if key.lower() == currentkey.lower():
                current = value
                break
        else:
            return
    return current

keys = []
for fn in sys.argv[1:]:
    with open(fn, 'rU') as f:
        data = vdf.load(f)

    runp = get_val_nocase('installscript.run process', data)
    if not runp:
        continue

    for name, runpinfo in runp.items():
        os = get_val_nocase('requirement_os.ostype', runpinfo)
        key = get_val_nocase('hasrunkey', runpinfo)
        if key:
            value = get_val_nocase('minimumhasrunvalue', runpinfo) or 1
            key = key.replace('\\\\', '\\')
            keys.append((key, name, int(value)))
        else:
            sys.stderr.write("Warning: no run key for %s" % name)
            proc = get_val_nocase('process 1', runpinfo)
            if proc:
                sys.stderr.write(": %s" % proc)
            sys.stderr.write("\n")

if keys:
    print("REGEDIT4")
    print("")
    for key, name, value in sorted(keys):
        print("[{}]".format(key))
        print('"{}"=dword:{:08x}'.format(name, value))
        print("")
else:
    sys.exit(1)
