#!/bin/bash

set -euo pipefail

usage () {
    cat <<END >&2
Usage: ${0##*/} [options] GAME_DIR [DEST_APP]

Options:

  -c             Given the GAME_DIR, heuristically check to see if this script should be used.
  -n             No copy. This disables copying the game dir into the app, so
                 you can make such arrangements yourself, or in a calling script.
  -r REL_PATH    Specify the relative path to the game dir from the
                 Contents/Resources dir in the app. Default: ../../Game.
END
    exit 1
}

process_arguments () {
    check_only=0
    no_copy=0
    rel_path=../../Game

    while getopts cnr:h opt; do
        case "$opt" in
            c)
                check_only=1
                ;;
            n)
                no_copy=1
                ;;
            r)
                rel_path="$OPTARG"
                ;;
            h|\?)
                usage
                ;;
        esac
    done
    shift $((OPTIND - 1))

    if [ $# -eq 0 ] || [ $# -gt 2 ]; then
        echo >&2 "Error: incorrect number of arguments"
        usage
    fi

    gamedir="$(cd "$1" && pwd)"
    if [ $# -gt 1 ]; then
        destdir="${2%.app}.app"
    else
        destdir="${gamedir##*/}.app"
    fi
    game_name="${destdir%.app}"
    game_name="${game_name##*/}"
}

check_supported () {
    if [ $check_only -eq 1 ]; then
        if [ -n "$(find "$gamedir"/ -iname dosbox.exe)" ]; then
            exit 0
        else
            exit 10
        fi
    fi
}

plist_add () {
    pb -c "Add '$(pb_escape_value "$1")' '${4:-string}' '$(pb_escape_value "$2")'" "$3"
}

pb () {
    /usr/libexec/PlistBuddy "$@"
}

pb_escape_value () {
    printf "%s" "$1" | sed "s/'/\\\\'/g"
}

locate_app_by_id () {
    mdfind "kMDItemContentType == 'com.apple.application-bundle' && kMDItemCFBundleIdentifier == '$*'"
}

adjust_identifier () {
    printf "%s\n" "$1" | tr '[:upper:]' '[:lower:]' | tr ' ' _
}


process_arguments "$@"
check_supported

if [ -e "$destdir" ]; then
    echo >&2 "Error: $destdir already exists, aborting"
    exit 2
fi


identifier="org.kergoth.gog.boxer.$(adjust_identifier "$game_name")"
wrapper_template="$(locate_app_by_id net.washboardabs.boxer-standalone | head -n 1)"

printf 'Boxer Standalone: %s\n' "$wrapper_template"
cp -a "$wrapper_template/." "$destdir/"
sed -i.bak -Ee "s/{{GAMEBOX_NAME}}/$game_name.boxer/; s/{{ORGANIZATION_NAME}}/kergoth@gmail.com/; s/{{ORGANIZATION_URL}}/mailto:kergoth@gmail.com/; s/{{BUNDLE_IDENTIFIER}}/$identifier/g; s/{{APPLICATION_NAME}}/$game_name/; s/{{YEAR}}/$(date +%Y)/;" "$destdir/Contents/Info.plist"
rm -f "$destdir/Contents/Info.plist.bak"
for i in UTImportedTypeDeclarations UTExportedTypeDeclarations CFBundleDocumentTypes; do
    /usr/libexec/PlistBuddy -c "Delete :$i" "$destdir/Contents/Info.plist"
done

gog_game_id="$(jq -rs 'map(select(.gameId == .rootGameId)) | .[0].gameId' "$gamedir"/goggame-*.info 2>/dev/null)" || true
if [ -n "$gog_game_id" ]; then
    pb -c "Delete BXHelpLinks" "$destdir/Contents/Info.plist" >/dev/null 2>&1 || true
    pb -c "Add BXHelpLinks array" "$destdir/Contents/Info.plist"
    gog_info="$gamedir/goggame-$gog_game_id.info"
    count=0
    jq <"$gog_info" '.supportTasks + .playTasks | .[] | select(.type == "URLTask") | .name + "|" + .link' | sed 's,^",,; s,"$,,' | \
        while IFS="|" read -r title url; do
            pb -c "Add BXHelpLinks:$count dict" "$destdir/Contents/Info.plist"
            plist_add "BXHelpLinks:$count:BXHelpLinkURL" "$url" "$destdir/Contents/Info.plist"
            plist_add "BXHelpLinks:$count:BXHelpLinkTitle" "$title" "$destdir/Contents/Info.plist"
            count="$((count + 1))"
        done
fi

boxer="$destdir/Contents/Resources/$game_name.boxer"
wrap-boxer -n "$gamedir" "$boxer"

if [ $no_copy -eq 0 ]; then
    cp -a "$gamedir" "$boxer/C.harddisk"
    "$boxer/finalize"

    if [ "$rel_path" != "../../Game" ]; then
        echo >&2 "Warning: copying game, ignoring specified rel_path $rel_path"
    fi
    ln -s "${boxer#$destdir/}/C.harddisk" "$destdir/Game"
else
    ln -s "../$rel_path" "$boxer/C.harddisk"
    cp -a "$(which lnr)" "$destdir/Contents/Resources/"
    cat <<END >"$destdir/finalize_wrapper"
#!/bin/sh
set -e
scriptdir="\$(cd "\$(dirname "\$0")" && pwd)"
cd "\$scriptdir/${boxer#$destdir/}"
gamedir="\$(cd C.harddisk && pwd -P)"
if [ -L C.harddisk ] && [ -d "\$gamedir" ]; then
    rm C.harddisk
    mv "\$gamedir" C.harddisk
    "\$scriptdir/Contents/Resources/lnr" C.harddisk "\$gamedir"
fi
./finalize
rm -f "\$scriptdir/Contents/Resources/lnr" "\$scriptdir/\${0##*/}"
END
    chmod +x "$destdir/finalize_wrapper"
fi

if [ -e "$boxer/game.icns" ]; then
    cp "$boxer/game.icns" "$destdir/Contents/Resources/app.icns"
else
    copymacicon "$boxer" "$destdir"
fi
