#!/bin/sh
# Wrap a .app in another .app
# - Move it to Contents/Resources/
# - Copy or link the icon
# - Copy the tags
# - Copy app metadata from the plist (name, display name, version, ..)
# - Symlink Extras
# - Arrange for supplementary apps to be available (i.e. Galaxy, Steam)

usage () {
    echo >&2 "${0##*/} [options] FROM_APP TO_APP"
    echo >&2
    echo >&2 "Options:"
    echo >&2 "  -n              Do not move FROM_APP into TO_APP"
    echo >&2 "  -r REL_DEST     FROM_APP will live in TO_APP/Contents/Resources/REL_DEST"
    echo >&2 "  -V              Do not copy version metadata"
    exit 2
}

copy_tags () {
    if which tag >/dev/null 2>&1; then
        tag -s "$(tag -lN "$1")" "$2"
    fi
}

copy_plist_info () {
    from="$1"
    to="$2"
    shift 2

    set -- CFBundleIdentifier CFBundleName CFBundleDisplayName
    if [ $copy_version -eq 1 ]; then
        set -- "$@" CFBundleVersion CFBundleShortVersionString
    fi
    for key; do
        from_value="$(pb -c "Print '$(pb_escape_value "$key")'" "$from/Contents/Info.plist" 2>/dev/null | sed 's,^",,g; s,"$,,g')"
        if [ -n "$from_value" ]; then
            plist_set "$key" "$from_value" "$to/Contents/Info.plist"
        fi
    done
}

plist_set () {
    if ! pb -c "Print '$(pb_escape_value "$1")'" "$3" >/dev/null 2>&1; then
        pb -c "Add '$(pb_escape_value "$1")' '${4:-string}' '$(pb_escape_value "$2")'" "$3"
    else
        pb -c "Set '$(pb_escape_value "$1")' '$(pb_escape_value "$2")'" "$3"
    fi
}

pb () {
    PlistBuddy "$@"
}

pb_escape_value () {
    printf "%s" "$1" | sed "s/'/\\\\'/g"
}


scriptdir="$(cd "$(dirname "$0")" && pwd)"
PATH="$scriptdir:$PATH:/usr/libexec"

rel_dest=
move=1
copy_version=1
while getopts nr:Vh opt; do
    case "$opt" in
        n)
            move=0
            ;;
        r)
            rel_dest="$OPTARG"
            ;;
        V)
            copy_version=0
            ;;
        \?|h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -ne 2 ]; then
    usage
fi

from_app="$1"
if [ ! -e "$from_app" ]; then
    echo >&2 "$from_app does not exist"
    exit 1
fi

to_app="$2"
if [ ! -e "$to_app" ]; then
    echo >&2 "$to_app does not exist"
    exit 1
fi

from_base="${from_app##*/}"
destpath="Contents/Resources/$rel_dest"
destpath="${destpath%/}"

copy_tags "$from_app" "$to_app"
copy_plist_info "$from_app" "$to_app"
copymacicon "$from_app" "$to_app"

mkdir -p "$to_app/$destpath"
if [ -e "$from_app/Extras" ]; then
    mkdir -p "$to_app/Extras"
    for i in "$from_app/Extras/"*; do
        if [ -e "$i" ]; then
            ln -s "../$destpath/$from_base/Extras/${i##$from_app/Extras/}" "$to_app/Extras/"
        fi
    done
fi

find "$from_app" -iname \*.app -mindepth 1 -maxdepth 1 | \
    grep -v Wineskin | while read extra_app; do
        ln -s "$destpath/$from_base/${extra_app#$from_app/}" "$to_app/"
    done

if [ $move -eq 1 ]; then
    mv "$from_app" "$to_app/$destpath/"
fi
