#!/bin/sh

wrap_install () {
    wrap_installdir="$1"
    wrap_out="$2"
    wrap_name="$3"

    new-gog-wrapper "$wrap_out" "$wrap_name"
    cp -a "$wrap_installdir" "$wrap_out/drive_c/GOG Games/$wrap_name"
    rm -f "$wrap_out/Game"
    ln -s "drive_c/GOG Games/$wrap_name" "$wrap_out/Game"
    rm -f "$wrap_out/finalize_gog" "$wrap_out/Contents/Resources/finalize_gog"
    finalize_gog "$wrap_out"
    if [ -d "$wrap_out" ]; then
        mv "$wrap_out" "$wrap_name.app"
    fi
}


if [ $# -eq 0 ]; then
    echo >&2 "Usage: ${0##*/} GOG_INSTALLDIR [GAME_NAME]"
    exit 2
fi

set -eu

scriptdir="$(cd "$(dirname "$0")" && pwd)"
PATH="$scriptdir:$PATH"

installdir="$(cd "$1" && pwd -P)"
if [ $# -gt 1 ]; then
    game_name="$2"
else
    game_name="${installdir##*/}"
fi
app_name="$(echo "$game_name" | tr -d :/).app"
if [ -e "$app_name" ]; then
    echo >&2 "Warning: $app_name already exists, skipping"
    continue
fi
echo >&2 "Creating $app_name"

tmp="$(mktemp -d "${0##*/}.XXXXXX")"
rmdir "$tmp"
trap 'rm -rf "$tmp"' EXIT INT TERM

wrap_install "$installdir" "$tmp" "$game_name"
