#!/bin/sh

titlecase () {
    if [ $# -gt 0 ]; then
        python -c 'import titlecase; import sys; print(titlecase.titlecase(" ".join(sys.argv[1:])))' "$@"
    else
        python -c 'import titlecase; import sys; print(titlecase.titlecase(sys.stdin.read().rstrip()))'
    fi
}

plist_set () {
    /usr/libexec/PlistBuddy -c "Set :$1 \"$2\"" "$3/Contents/Info.plist"
}

usage () {
    echo >&2 "${0##*/} GOG_DL_DIR APP_NAME"
    exit 1
}


if [ $# -eq 0 ]; then
    usage
fi

gog_dl_dir="$1"
exepath="$(find "$gog_dl_dir" -depth 1 -name "setup_*.exe" | sort -r | head -n 1)"
if [ -n "$exepath" ]; then
    name_fn="$(basename "$exepath" | py -x 're.match(r"setup_([a-zA-Z0-9_]+)_(([0-9]\.)+[0-9])", x).group(1)' 2>/dev/null)"
fi
if [ $# -eq 1 ]; then
    if [ -z "$name_fn" ]; then
        usage
    fi
    app_name="$(echo "$name_fn" | tr _ ' ' | titlecase)"
else
    app_name="$2"
fi
APP_NAME="${app_name}.app"
if [ -e "$APP_NAME" ]; then
    echo >&2 "$APP_NAME already exists, aborting"
    exit 2
fi

set -e

scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
PATH="$scriptdir:$PATH"

tmp="$(mktemp -d "${0##*/}.XXXXXX")"
ditto "${0%/*}/GOG Galaxy (Windows).app" "$tmp"
rm -f "$tmp/Games" "$tmp/Client"
plist_set CFBundleIdentifier "org.kergoth.gog.$(echo "$app_name" | tr 'A-Z' 'a-z' | tr ' ' '_')" "$tmp"
plist_set CFBundleName "$app_name" "$tmp"
plist_set CFBundleShortVersionString GOG "$tmp"
/usr/libexec/PlistBuddy -c "Add :CFBundleDisplayName string \"$app_name\"" "$tmp/Contents/Info.plist"
gog-extract-extras "$gog_dl_dir" "$tmp"
for i in "$tmp/Extras/"*; do
    new="$(echo "${i#$tmp/Extras/}" | sed -n -e "s/^$app_name //p")" || true
    if [ -n "$name_fn" ]; then
        new2="$(echo "${i#$tmp/Extras/}" | sed -n -e "s/^$(echo "$name_fn" | tr _ ' ' | titlecase) //p")" || true
    else
        new2=
    fi
    if [ -n "$new" ]; then
        mv -v "$i" "$tmp/Extras/$new"
    elif [ -n "$new2" ]; then
        mv -v "$i" "$tmp/Extras/$new2"
    fi
done
# ln -s "$gog_dl_dir" "$app_name Installer"
cp "$scriptdir/finalize_gog" "$tmp/Contents/Resources/"
cat >>"$tmp/finalize" <<END
#!/bin/sh
scriptdir="\$(cd "\$(dirname "\$0")" && pwd -P)"
"\$scriptdir/Contents/Resources/finalize_gog" "\$scriptdir" && \
    rm -fv "\$0" && \
    rm -fv "\$scriptdir/Contents/Resources/finalize_gog"
END
chmod +x "$tmp/finalize"
mv "$tmp" "$APP_NAME"

if which tag >/dev/null 2>&1; then
    tag -a Game "$APP_NAME"
fi
