#!/bin/sh

wrap_installer () {
    wrap_exe="$1"
    wrap_out="$2"
    wrap_name="$3"

    new-gog-wrapper "$wrap_out" "$wrap_name"
    install-gog "$wrap_exe" "$wrap_out/Games/$wrap_name"
    rm -f "$wrap_out/Game"
    ln -s "$(readlink "$wrap_out/Games")/$wrap_name" "$wrap_out/Game"
    rm -f "$wrap_out/finalize_gog" "$wrap_out/Contents/Resources/finalize_gog"
    finalize_gog "$wrap_out"
    if [ -d "$wrap_out" ]; then
        mv "$wrap_out" "$wrap_name.app"
    fi
}

if [ $# -eq 0 ]; then
    echo >&2 "Usage: ${0##*/} GOG_INSTALLER"
    exit 2
fi

set -e

scriptdir="$(cd "$(dirname "$0")" && pwd)"
PATH="$scriptdir:$PATH"

installer="$1"
game_name="$(gog-installer-get-name "$installer")"
app_name="$(echo "$game_name" | tr -d :/).app"
if [ -e "$app_name" ]; then
    echo >&2 "Warning: $app_name already exists, skipping"
    exit 1
fi
echo >&2 "Creating $app_name"

tmp="$(mktemp -d "${0##*/}.XXXXXX")"
rmdir "$tmp"
trap 'rm -rf "$tmp"' EXIT INT TERM

wrap_installer "$installer" "$tmp" "$game_name"
