#!/bin/sh

default="5 - Backlog"

if [ $# -eq 0 ]; then
    echo >&2 "${0##*/} GAME_NAME [GAME_NAME..]"
    exit 1
fi

for app; do
    arg="${app%.app}.app"
    if [ -d "$arg" ] && [ ! -h "$arg" ]; then
        # Assuming arg is source, not dest
        source="$arg"
        dest="$default"
    else
        dest="$(dirname "$arg")"
        if [ "$dest" = "." ]; then
            dest="$default"
        fi
        source=/dev/null
    fi
    destfn="$(basename "$arg")"
    rm -vf "$dest/$destfn"
    ln -vs "$source" "$dest/$destfn"
    ./score-games "$dest/$destfn"
    ./howlongtobeat-games "$dest/$destfn"
done
