#!/bin/sh

find_app_symlinks_resolved () {
    find "$@" -iname \*.app -prune -type l -print -maxdepth 3 | \
        tr '\n' '\0' | xargs -0 -n 1 abs_readlink
}

{
    find /Volumes/My\ Passport/Games*/ -iname \*.app -prune -type d -print -maxdepth 3 | grep -Ev 'Setup|Launcher|-64'
    find_app_symlinks_resolved /Volumes/My\ Passport/Games*/
    if [ -e /Volumes/Games\ Archive ]; then
        find /Volumes/Games\ Archive/Games*/ -iname \*.app -prune -type d -print -maxdepth 3 | grep -Ev 'Setup|Launcher|-64'
        find_app_symlinks_resolved /Volumes/Games\ Archive/Games*/
    else
        echo >&2 "Warning: Games Archive is not mounted"
    fi
    tag-find -p /Volumes/My\ Passport/OpenEmu\ Library Game
} | grep -Ev '\.Trashes|Utilities|Archived|Pending|Backup' | sed 's,//,/,g' | sort -u
