#!/bin/sh

scriptdir="$(cd "$(dirname "$0")" && pwd)"
cd "$(dirname "$0")"

existing="$(mktemp -t "${0##*/}.XXXXXX")"
trap 'rm -f "$existing"' EXIT INT TERM
"$scriptdir/existing-games" >>"$existing"

which aliasPath >/dev/null 2>&1
aliaspath_check=$?

mdfind -onlyin "$PWD" "kMDItemKind = 'Alias'" "$@" | \
    grep -v "By Tag" | \
    while read alias; do
        if [ $aliaspath_check -eq 0 ]; then
            alias_path="$(aliasPath "$alias")"
            root="$(echo "$alias_path" | cut -d/ -f2)"
            if [ "$root" = "Volumes" ]; then
                volume="$(echo "$alias_path" | cut -d/ -f3)"
                if [ ! -e "/Volumes/$volume" ]; then
                    # echo >&2 "$volume isn't mounted, skipping $alias"
                    continue
                fi
            fi
        fi

        resolved="$("$scriptdir/resolve-alias" "$alias" 2>/dev/null)"
        if [ $? -ne 0 ] || ! grep -Fqx "$resolved" "$existing"; then
            echo "$alias"
        fi
    done
