#!/bin/sh

for toml in _metadata/*.toml; do
    score="$(toml-get metacritic.score <"$toml" 2>/dev/null)" || continue
    if [ "$score" = "0" ]; then
        user_score="$(toml-get metacritic.user_score <"$toml")"
        if [ "$user_score" != "0.0" ]; then
            score="$(echo "$user_score" | tr -d .)"
        fi
    fi
    mc_game="$(toml-get metacritic.game <"$toml" 2>/dev/null)" || continue
    if [ "$score" != "0" ]; then
        printf '%s\t%s\t%s\n' "$(basename "${toml%.toml}")" "$score"
    fi
done | sort -nrs -k2,2 -t"	"
