#!/bin/sh

for toml in _metadata/*.toml; do
    if grep -q '##invalid##' "$toml"; then
        continue
    fi

    toml-get metacritic.game metacritic.score metacritic.user_score <"$toml" | \
        {
            read mc_game
            read score
            read user_score
            if [ "$score" = "0" ]; then
                if [ "$user_score" != "0.0" ]; then
                    score="$(echo "$user_score" | tr -d .)"
                else
                    continue
                fi
            fi
            printf '%s\t%s\t%s\n' "$(basename "${toml%.toml}")" "$score"
        }
done | sort -nrs -k2,2 -t"	"
