#!/bin/sh

scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
PATH="$scriptdir/scoring-methods:$scriptdir:$PATH"
. "$scriptdir/common-include"

tab="$(printf '\t')"
for gametitle; do
    gametitle="$(title_sanitize "$gametitle")"
    echo "Scoring $gametitle.."
    if ! tomlq -f game-scores.toml "$gametitle.identifiers" >/dev/null 2>&1; then
        identifier="$(search "$gametitle" | cut -d"$tab" -f1)"
        set-score-info "$gametitle" "$identifier" >&2 || break
        identifiers="$identifier"
    else
        identifiers="$(tomlq -f game-scores.toml "$gametitle" | toml-get-array-lines identifiers | tr '\n' ' ')"
    fi
    for identifier in $identifiers; do
        if [ -n "$identifier" ]; then
            method="${identifier%:*}"
            identifier="${identifier#*:}"
            title="$(tomlq -f scoring.toml "$method.games.$identifier.title")"
            scores="$(tomlq -f scoring.toml "$method.games.$identifier" | toml-get-array-lines scores | tr '\n' '\t')"
            printf '%s\t%s\t%s\n' "$gametitle" "$title" "$scores"
        fi
    done
    # if [ -n "$identifier" ]; then
    #     printf '%s\t%s\n' "$gametitle" "$(toml-get-array-lines -f game-scores.toml "$gametitle.scores" | tr '\n' '\t')"
    # fi
done
