#!/bin/sh

scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
PATH="$scriptdir/scoring-methods:$scriptdir:$PATH"
. "$scriptdir/common-include"

gametitle="$(title_sanitize "$1")"
shift

tomlfile="game-scores.toml"
toml-set-string-array -f "$tomlfile" "$gametitle.identifiers" "$@"
for identifier; do
    if [ -z "$identifier" ]; then
        continue
    fi
    method="${identifier%:*}"
    identifier="${identifier#*:}"
    scores="$(tomlq -f scoring.toml "$method.games.$identifier" | toml-get-array-lines scores | tr '\n' '\t')"
    if [ -n "$scores" ]; then
        title="$(tomlq -f scoring.toml "$method.games.$identifier.title")"
        printf '%s\t%s\t%s\t%s\n' "$gametitle" "$method" "$title" "$scores"
        toml-set-string-array -f "$tomlfile" "$gametitle.scores" $scores
        exit 0
    fi
done
toml-set-string-array -f "$tomlfile" "$gametitle.scores" ""
