#!/bin/sh

scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
PATH="$scriptdir/scoring-methods:$scriptdir:$PATH"
. "$scriptdir/common-include"

for gametitle; do
    gametitle="$(title_sanitize "$gametitle")"
    tomlq -f game-scores.toml "$gametitle" | toml-get-array-lines identifiers | \
        tr '\n' '\0' | xargs -0 score-by-id
done
